review (13 sprint)
TheSorryGuy/sprint12 pull request #2
Opened 2020-04-24 03:30 UTC by TheSorryGuy

выполнил задания из описания проекта:
исключение для линтера
подключил базу данных
создал схемы и модели для сущностей пользователя и карточки
по указанным запросам сервер отдает соответствующую информацию, или ошибки, если что то пошло не так или запросы не корректны
папки с фронтендом и файлами карточек и пользователей удалил
выполнил дополнительное задание, добавив дополнительные роуты

2020-04-25 06:40 UTC, aarefiev requested changes
Общее впечатление - хорошая работа :+1:, но есть недопонимание какие нештатные ситуации бывают и как их обрабатывать.

Хорошее описание проекта. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели) :book: . Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Линтер не запускается, ошибка конфигурации. Отдельного конфигурационного файл со всеми настройками для работы сервера не обнаружено. Схемы моделей настроены корректно. Роуты настроены корректно, но есть ошибки в кодах ответов и нештатные ситуации не обрабатываются. Централизованная обработка несуществующего роута есть, работает. Сервер локально запускается в режиме хот-релоада и без, ошибок в консоли не возникает. Временные файлы игнорируются.

Найдено несколько ошибок и улучшений.Краткий список ошибок и улучшений представлен ниже, расширенные комментарии непосредственно в коде.

**Нужно исправить:**
1. Линтер не запускается.
2. При возникновении ошибки при получении пользователя по id возвращается 404.
3. При получении пользователя по id, который не существует в базе, возвращается 200.
4. При возникновении ошибки при создании пользователя возвращается 400.
5. При возникновении ошибки при обновлении профиля возвращается 400.
6. При возникновении ошибки при создании карточки возвращается 400.
7. При возникновении ошибки при установке лайка на карточку возвращается 400.
8. При установке лайка на карточку, которая не существует в базе, возвращается 200.
9. При возникновении ошибки при удалении лайка с карточки возвращается 400.
10. При удалении лайка с карточки, которая не существует в базе, возвращается 200.
11. При возникновении ошибки при удалении карточки возвращается 400.
12. При удалении карточки, которая не существует в базе, возвращается 200.

**Можно лучше:**
1. Вынести настройки в отдельный конфигурационный файл.
2. `useUnifiedTopology`.
3. Использовать модуль `validator` для валидации строк формата `URL`.
4. Доработать README.md.
5. Проводить назначение обработчиков до запуска сервера.

2020-04-25 06:40 UTC, aarefiev commented on app.js
>  const { PORT = 3000 } = process.env;
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Если оставить определение значений в коде, то возникает несколько очевидных проблем:
- изменение какой-то настройки требует изменений всех файлов, где она используется,
- нельзя использовать отдельные настройки для разработки и продакшена

Лучше создать отдельный файл (например, `config.js`) и в нём уже заполнять те настройки, которые будут использоваться в проекте (например, секретный ключ, порт сервера или адрес для подключения к базе данных). Далее этот файл подключать в тех файлах, где необходимо получить значения. Пример файла:
```js
module.exports.PORT = process.env.PORT || 3000;
module.exports.DATABASE_URL = 'mongodb://localhost:27017/mestodb';
```

2020-04-25 06:40 UTC, aarefiev commented on app.js
> +});
Можно лучше: вынести настройки в отдельный конфигурационный файл.
Адрес и список параметров для подключения к базе данных.

2020-04-25 06:40 UTC, aarefiev commented on models/card.js
> +    match: /https?:\/\/(www.)?(((2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])\.){3}(2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])|([\w\-]{2,}(\.[\w\-]{2,})*\.[a-zA-Z]{2,}))(:\d{2,5})?(\/[\d\/a-zA-Z-]+#?)?/,
Можно лучше: использовать модуль `validator` для валидации строк формата `URL`.
Модуль: https://www.npmjs.com/package/validator .
Нужный метод: `.isURL`.

2020-04-25 06:40 UTC, aarefiev commented on models/user.js
> +    match: /https?:\/\/(www.)?(((2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])\.){3}(2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])|([\w\-]{2,}(\.[\w\-]{2,})*\.[a-zA-Z]{2,}))(:\d{2,5})?(\/[\d\/a-zA-Z-]+#?)?/,
Можно лучше: использовать модуль `validator` для валидации строк формата `URL`.

2020-04-25 06:40 UTC, aarefiev commented on .eslintrc
> +  "no-underscore-dangle": ["error", { "allow": ["_id"] }]
Нужно исправить: линтер не запускается.
```bash
$ npx eslint --ext .js .
ESLint configuration in .eslintrc is invalid:
	- Unexpected top-level property "no-underscore-dangle".
```

Ожидается, что линтер запустится и ошибок маркированных **error** не будет (**warning** допускается).

2020-04-25 06:40 UTC, aarefiev commented on README.md
>  This is a **training project**
Можно лучше: доработать README.md.
Текущее описание очень хорошо выполнено, но вопрос инструкции как равзернуть проект не очень раскрыт. 

Дополнительно скину ресурсы, которые помогут его улучшить:
- статья "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)".
- примеры шаблонов для README:
  - https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
  - https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-04-25 06:40 UTC, aarefiev commented on app.js
>    });
Можно лучше: проводить назначение обработчиков до запуска сервера.

2020-04-25 06:40 UTC, aarefiev commented on app.js
> +});
Можно лучше: `useUnifiedTopology`.
> (node:16171) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.

2020-04-25 06:40 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(404).send({ message: 'Нет пользователя с таким id', error: err.message }));
Нужно исправить: 
- при возникновении ошибки при получении пользователя по `id` возвращается 404,
- при получении пользователя по `id`, который не существует в базе, возвращается 200

Видов ошибок много, у каждого из них есть свой отдельный HTTP код. По-умолчанию, все ошибки, которые возникают на сервере считаются ошибкой сервера - это [500 Internal Server Error](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/500).

Но как же вернуть 404, когда пользователь не найден? Во первых стоит разобраться, когда мы можем возвращать 404.

В _MongoDB_ у идентификатора есть определенный формат (цифробуквенная строка размером в 24 символа). Если попытаться передать идентификатор отличный от поддерживаемого формата, то будет брошено исключение. Например, запрос `GET /users/1`:
```bash
Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"user\"
```
В этом случае мы не можем отправлять 404, потому что БД не работает с такими идентификаторами. В этом случае нужно отправлять 500.

Другой пример, запрос `GET /users/5e9b2988b9b9280dc5db6092`. Ответ с кодом 200:
```json
[]
```
В этом случае у нас корректный идентификатор и `userById` равен `null`. В _Mongoose_ при получении записи не возникает исключения, если запись отсутствует в базе данных. Вот мы и подошли к 404, именно здесь, когда запись отсутствует мы можем возвращать 404.

2020-04-25 06:40 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось создать пользователя', error: err.message }));
Нужно исправить: при возникновении ошибки при создании пользователя возвращается 400.
По-умолчанию, все ошибки, которые возникают на сервере считаются ошибкой сервера - это [500 Internal Server Error](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/500).
В контроллере 400 ошибки не может быть, потому что он уже работает с проверенными данными. А вот была ли реализована проверка данных - это уже вопрос другой практики и он будет рассматриваться позже.

2020-04-25 06:40 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось обновить информацию о пользователе', error: err.message }));
Нужно исправить: при возникновении ошибки при обновлении профиля возвращается 400.
Аналогично комментарию для создания пользователя.

2020-04-25 06:40 UTC, aarefiev commented on controllers/users.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось обновить аватар', error: err.message }));
Нужно исправить: при возникновении ошибки при обновлении профиля возвращается 400.
Аналогично комментарию для создания пользователя.

2020-04-25 06:40 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось создать карточку', error: err.message }));
Нужно исправить: при возникновении ошибки при создании карточки возвращается 400.
Аналогично комментарию для создания пользователя.

2020-04-25 06:40 UTC, aarefiev commented on controllers/cards.js
> +  .catch((err) => res.status(400).send({ message: 'Не удалось поставить лайк', error: err.message }));
Нужно исправить: 
- при возникновении ошибки при установке лайка на карточку возвращается 400,
- при установке лайка на карточку, которая не существует в базе, возвращается 200

Аналогично комментарию для получения пользователя по `id`.
Примеры запросов и корректных кодов ответов:
- `PUT /cards/5ea3d75f7def7d3f2b363793/likes` (`id` существует в базе) - 200 (можно и 201),
- `PUT /cards/5ea3d75f7def7d3f2b363794/likes`  - 404,
- `PUT /cards/1/likes` - 500

2020-04-25 06:40 UTC, aarefiev commented on controllers/cards.js
> +  .catch((err) => res.status(400).send({ message: 'Не удалось удалить лайк', error: err.message }));
Нужно исправить: 
- при возникновении ошибки при удалении лайка с карточки возвращается 400,
- при удалении лайка с карточки, которая не существует в базе, возвращается 200

Аналогично комментарию для получения пользователя по `id`.
Примеры запросов и корректных кодов ответов:
- `DELETE /cards/5ea3d75f7def7d3f2b363793/likes` (`id` существует в базе) - 200,
- `DELETE /cards/5ea3d75f7def7d3f2b363794/likes`  - 404,
- `DELETE /cards/1/likes` - 500

2020-04-25 06:40 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось удалить карточку', error: err.message }));
Нужно исправить: 
- при возникновении ошибки при удалении карточки возвращается 400,
- при удалении карточки, которая не существует в базе, возвращается 200

Аналогично комментарию для получения пользователя по `id`.
Примеры запросов и корректных кодов ответов:
- `DELETE /cards/5ea3d75f7def7d3f2b363793` (`id` существует в базе) - 200,
- `DELETE /cards/5ea3d75f7def7d3f2b363794`  - 404,
- `DELETE /cards/1` - 500

2020-04-26 00:59 UTC, TheSorryGuy commented
во второй итерации;
- вынес настройку сервера в отдельный файл
- изменил сообщения и коды ошибок в соответствии с правками
- добавил валидацию ссылок с помощью модуля validator
- исправил ошибку в настройке линтера
- исправил ошибки линтинга
- переместил создание сервера
- доработал readme

2020-04-26 18:31 UTC, aarefiev requested changes
Очень хорошо. Часть ошибок всё еще не решены. Постарался раскрыть вопрос подробнее.

Нужно исправить:
1. При возникновении ошибки при получении пользователя по `id` возвращается 404.
2. При создании карточки возвращается 500.
3. При возникновении ошибки при удалении карточки возвращается 400.
4. При удалении карточки, которая не существует в базе, возвращается 200.
5. При возникновении ошибки при установке лайка на карточку возвращается 404.
6. При возникновении ошибки при удалении лайка с карточки возвращается 404.

2020-04-26 18:31 UTC, aarefiev commented on models/card.js
> +        validator.isUrl(item);
Нужно исправить: при создании карточки возвращается 500.
```suggestion
        validator.isURL(item);
```

2020-04-26 18:31 UTC, aarefiev commented on controllers/users.js
> +  res.status(500).send({ message: 'Некорректный id' });
Нужно исправить: при возникновении ошибки при получении пользователя по `id` возвращается 404.
Проблема не исправлена. Потому что сейчас если будет выполнен код внутри условия и произойдёт любая ошибка, то клиенту будет отправлено 404. А на самом деле может быть и ошибка на сервере.

Метод `.orFail()` это хорошо, отлично что сами догадались. Но, обработку стоит делать по-другому.

Первым делом нужно сделать единый `.catch()` блок, который будет отлавливать любые ошибки в контроллере. Базовым кодом ошибки должен быть 500. Выглядеть это будет примерно так:
```js
user.find()
  .then()
  .catch((err) => res.status(500).send({ message: 'Ошибка на сервере', error: err.message });
```

Далее для обработки 404 нужно как-то прокидывать этот код в `.catch()` блок. Лучший вариант - создать отдельный модуль ошибки и определить для него свойство, в котором будет нужный HTTP код. Пример для 404:
```js
// errors/notFoundError.js
class NotFoundError extends Error {
  constructor(message) {
    super(message);
    this.statusCode = 404;
  }
}

module.exports = NotFoundError;
```

Далее подключаем `.orFail()` и добавляем использование кода из `err`:
```js
user.find()
  .orFail(new NotFoundError('Нет пользователя с таким `id`'))
  .then()
  .catch((err) => {
    const statusCode = err.statusCode || 500;
    res.status(statusCode).send({ message: statusCode === 500 ? 'Ошибка на сервере' : err.message });
  });
```

2020-04-26 18:31 UTC, aarefiev commented on controllers/cards.js
> +    .catch((err) => res.status(400).send({ message: 'Не удалось удалить карточку', error: err.message }));
Нужно исправить:
- при возникновении ошибки при удалении карточки возвращается 400,
- при удалении карточки, которая не существует в базе, возвращается 200

Не исправлено. Детали: https://github.com/TheSorryGuy/sprint12/pull/2/files#r414994847 .
Особенности ожидаемой реализации можно посмотреть в комментарии для получения пользователя.

2020-04-26 18:31 UTC, aarefiev commented on controllers/cards.js
> +  res.status(500).send({ message: 'Некорректный id' });
Нужно исправить: при возникновении ошибки при установке лайка на карточку возвращается 404.
Аналогично комментарию для получения пользователя.

2020-04-26 18:31 UTC, aarefiev commented on controllers/cards.js
> +  res.status(500).send({ message: 'Некорректный id' });
Нужно исправить: при возникновении ошибки при удалении лайка с карточки возвращается 404.
Аналогично комментарию для получения пользователя.

2020-04-27 01:08 UTC, TheSorryGuy commented
Исправил статусы ответов, надеюсь что понял вас верно в этот раз. сожалею, что вам приходится перепроверять работу из за таких пустяковых ошибок, спасибо за терпение и подробные комментарии.

2020-04-27 18:31 UTC, aarefiev requested changes
Отлично. Обработку побороли, надеюсь в следующий раз ошибок не будет. К сожалению, я в прошлые разы пропустил одну досадную ошибку. Её потребуется исправить перед мержем.

**Нужно исправить:** валидация поля не работает.

2020-04-27 18:31 UTC, aarefiev commented on models/user.js
> +      },
Нужно исправить: валидация поля не работает.
Согласно документации ожидается, что метод валидации вернёт `true/false`. Это и будет означать, прошла валидация или нет.
В данном случае нет возврата значения, тк стрелочная функция автоматически возвращает значение только в случае короткой записи (иначе ожидается, что будет использована конструкция `return`):
```suggestion
      validator: (item) => validator.isURL(item),
```

2020-04-27 18:31 UTC, aarefiev commented on models/card.js
> +    },
Нужно исправить: валидация поля не работает.
Аналогично комментарию для модели `User`.

2020-04-27 18:47 UTC, TheSorryGuy commented
исправил функцию валидатора

2020-04-27 19:00 UTC, aarefiev commented
> исправил функцию валидатора

@TheSorryGuy  аккуратнее, линтер не дремлет :eyes: .
```bash
$ npx eslint --ext .js .

/home/jmi/work/ya-reviews/sprint12/models/card.js
  15:49  error  Missing trailing comma  comma-dangle

/home/jmi/work/ya-reviews/sprint12/models/user.js
  21:49  error  Missing trailing comma  comma-dangle

✖ 2 problems (2 errors, 0 warnings)
  2 errors and 0 warnings potentially fixable with the `--fix` option.
```

2020-04-27 19:12 UTC, TheSorryGuy commented
исправил проблему линтера

2020-04-27 19:17 UTC, aarefiev approved these changes
Отлично, ошибки исправлены. Новых не обнаружено. Работа приниимается :rocket: .

2020-05-07 18:45 UTC, merged