sprint 15
TheSorryGuy/sprint12 pull request #4
Opened 2020-05-21 21:49 UTC by TheSorryGuy

выполнил задания спринта
- добавил централизованный мидлвэр для обработки ошибок
- запросы валидируются до того, как попадут в контроллер
- осуществлен сбор логов
- ссылки на домен и ip в readme
- на сервере есть .env файл 
- добавил код для краш теста, у меня вроде работает
- сертификаты для https подключил

2020-05-22 19:26 UTC, aarefiev requested changes
Отличная работа. Выполнено дополнительное задание :+1:.

Есть отлично оформленное описание проекта. Проект хорошо структурирован, элементы сгруппированы в группы по принадлежности (роуты, контроллеры, модели, мидлвары, модули ошибок). Для статической проверки синтаксиса подключен линтер `eslint`, устанавливающий соответствие стайлгайду _Airbnb_. Запуск линтера завершается без ошибок. Для роутов назначена валидация согласно заданию, но не везде где это нужно. Централизованный обработчик ошибок реализован, работает. Обработчик несуществующего роута реализован, работает. Мидлвара авторизации реализована, работает. Запросы логируются в `request.log`, ошибки в `error.log`. Временные файлы игнорируются. Сервер локально запускается с хот релоадом и без, ошибок в консоли не обнаружено. Публичный сервер доступен по домену и протоколу HTTPS и по IP по HTTP. Сертификат валиден. Секретный ключ на публичном сервере отличается от используемого локально. Сервер автоматически восстанавливает состояние после обращения на роут краш теста.

Ошибок немного. Ниже краткий список ошибок и улучшений, развернутые комментарии непосредственно в коде.

**Нужно исправить:**
1. Не реализована схема на уровне роутинга.
2. При попытке удалить карточку другого пользователя возвращается 404.

**Можно лучше:**
1. Назначать обработчики до запуска сервера.
2. Использовать методы mongoose при сравнении идентификаторов.
3. Бросать исключение при необходимости.
4. Отправлять результат сохранения в бд на клиент.
5. Вынести регулярное выражение для проверки URL в конфигурационный файл/отдельный модуль.
6. Вынести подключение роутов в отдельный файл.

2020-05-22 19:26 UTC, aarefiev commented on app.js
>      res.status(404).send({ message: 'Запрашиваемый ресурс не найден' });
Можно лучше: назначать обработчики до запуска сервера.

2020-05-22 19:26 UTC, aarefiev commented on controllers/cards.js
>      .then((cardExist) => {
Можно лучше: использовать методы `mongoose` при сравнении идентификаторов.
Где: https://github.com/TheSorryGuy/sprint12/blob/02db47c32cc552a893e0cff0e972c59e7efea426/controllers/cards.js#L23
В библиотеке `mongoose` `card` - это экземпляр класса `Document`. У этого класса есть отдельный метод, который отвечает за проверку на равенство - это метод [`.equals()`](https://mongoosejs.com/docs/api.html#document_Document-equals). Его лучше использовать, потому что в этой практике поле `cardExist` - это объект, а `req.user._id` - это строка. И чтобы их сравнить нужно приводить типы. Если использовать метод библиотеки, то приведение типов делать не нужно.

2020-05-22 19:26 UTC, aarefiev commented on controllers/users.js
> +    })
Можно лучше: бросать исключение при необходимости.
`.orFail()` принимает на вход функцию, либо экземпляр ошибки и выполняет отклонение промиса. Передача функции, в которой вручную происходит бросание исключения выглядит как использование функционала, который непонятно как работает. Как минимум нужно стараться использовать функционал по назначению.

2020-05-22 19:26 UTC, aarefiev commented on controllers/users.js
>        name, about, avatar, email, password: hash,
Можно лучше: отправлять результат сохранения в бд на клиент.
Где: https://github.com/TheSorryGuy/sprint12/blob/02db47c32cc552a893e0cff0e972c59e7efea426/controllers/users.js#L35
Вполне возможно, что при сохранении записи в базу данных часть данных может быть преобразована. Поэтому лучше отправлять то, что пришло в колбэке, а не данные, которые были переданы клиентом.

2020-05-22 19:26 UTC, aarefiev commented on app.js
> +const URLregex = /^https?:\/\/(www.)?(((2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])\.){3}(2[0-5]{2}|2[0-4][0-9]|1?[1-9]?[0-9])|([\w-]{2,}(\.[\w-]{2,})*\.[a-zA-Z]{2,}))(:\d{2,5})?(\/[\d/a-zA-Z-]+#?)?$/;
Можно лучше: вынести регулярное выражение для проверки URL в конфигурационный файл/отдельный модуль.
Один и тот же код определяется в нескольких местах:
https://github.com/TheSorryGuy/sprint12/blob/02db47c32cc552a893e0cff0e972c59e7efea426/routes/cards.js#L5
https://github.com/TheSorryGuy/sprint12/blob/02db47c32cc552a893e0cff0e972c59e7efea426/routes/users.js#L5

2020-05-22 19:26 UTC, aarefiev commented on app.js
> +app.use(errorHandler);
Можно лучше: вынести подключение роутов в отдельный файл.
Уровень `app.js` является точкой входа в проект. Обычно понимание проще, когда мы оперируем абстракциями, а не конкретной реализацией. Конечно в текущем виде роуты для `/users`, `/cards`, обработка несуществующего роута уже абстрагирована, но можно добавить ещё одну, которая объединяет их общим - всё это роуты приложения. К тому же внедрение этой абстракции позволит оставить код, назначающий роуты в одном файле, что сделает код более читабельным.

Например, можно создать `routes/index.js` файл, в который перенести подключение всех роутов + обработку несуществующего роута. А в `app.js` оставить лишь подключение:
```js
const routes = require('./routes');

app.use(routes);
```

2020-05-22 19:26 UTC, aarefiev commented on app.js
>  app.post('/signin', login);
Нужно исправить: не реализована схема на уровне роутинга.
Ожидается, что при авторизации будет схема, которая проверяет тело запроса:
- `email` - строка, формат e-mail, обязательное поле,
- `password` - строка, количество символов от 8 до 30, обязательное поле

2020-05-22 19:26 UTC, aarefiev commented on routes/users.js
>  usersRouter.get('/users/:_id', getUserById);
Нужно исправить: не реализована схема на уровне роутинга.
Ожидается, что для валидации `id` будет схема, которая проверяет параметры запроса:
- `id` - строка, формат цифробуквенная строка, количество символов равно 24, обязательное поле

2020-05-22 19:26 UTC, aarefiev commented on routes/cards.js
>  cardsRouter.delete('/cards/:cardId/likes', removeLike);
Нужно исправить: не реализована схема на уровне роутинга.
Ожидается, что для валидации `id` будет схема, которая проверяет параметры запроса:
- `id` - строка, формат цифробуквенная строка, количество символов равно 24, обязательное поле

2020-05-22 19:26 UTC, aarefiev commented on controllers/cards.js
>      .then((cardExist) => {
Нужно исправить: при попытке удалить карточку другого пользователя возвращается 404.
Где: https://github.com/TheSorryGuy/sprint12/blob/02db47c32cc552a893e0cff0e972c59e7efea426/controllers/cards.js#L24
Для ситуаций, когда доступ на выполнение какой-либо операции запрещен существует отдельный код - [403 Forbidden](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/403).

2020-05-22 22:34 UTC, TheSorryGuy commented
исправил все замечания, в том числе "можно лучше", кроме одного, про перенос подключения роутов в один файл. боюсь, что начну путаться и это будет надолго, а дедлайн уже близко, но спасибо за комментарий, я с ним согласен, и буду про это помнить. все таки файл app.js действительно выглядит захламленным

2020-05-23 15:01 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены. Новых не обнаружено.
Работа принимается :rocket:.

**Можно лучше:**
1. Запускать сервер только после подключения к базе данных.
2. Не делать лишний запрос к базе данных.

2020-05-23 15:01 UTC, aarefiev commented on app.js
>  mongoose.connect(DATABASE_URL, SERVER_PARAMS);
Можно лучше: запускать сервер только после подключения к базе данных.
Смысл в том, что текущий сервер в основном работает только с базой данных. Поэтому, если подключение к базе данных не удалось установить, то сервер будет всегда отдавать 500 (кроме несуществующего роута).
Мы в практике не делаем на этом акцент, хотя в реальной жизни база данных может быть недоступной. Но здесь явно вы не поняли суть, почему `mongoose.connect()` должен быть до `app.listen()`.
Можно использовать колбэк для `monoose.connect()`, если будет ошибка, то собщить об этом либо поднять сервер, те `app.listen(PORT)`;

2020-05-23 15:01 UTC, aarefiev commented on controllers/users.js
> +    .then((dbUser) => res.send(dbUser))
Можно лучше: не делать лишний запрос к базе данных.
Метод `.create()` возвращает результат записи в базу данных. Нужно только его обработать, удалить из объекта секретные данные (пароль, в реальной жизни может быть что-то ещё). И отдать клиенту.

2020-05-25 15:10 UTC, merged